/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package VISTA;

/**
 *
 * @author Pc
 */
public class IMPRIMIR extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;

    /**
     * Creates new customizer IMPRIMIR
     */
    public IMPRIMIR() {
        initComponents();
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jbtnRealizarCalculo = new javax.swing.JButton();
        jbtnImprimirVenta = new javax.swing.JButton();
        jblCantidadProductos = new javax.swing.JLabel();
        jtxtCantidadProductos = new javax.swing.JTextField();
        jLabel72 = new javax.swing.JLabel();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtIGV = new javax.swing.JTextField();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jtxtImporte = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jtxtIDProductoVenta = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jtxtDescripcionVenta = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jtxtPrecioVenta = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxtStockVenta = new javax.swing.JTextField();
        jbtnConsultaProductosVenta = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jbtnConsultaClientesVenta = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jlblNumBoleta = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtblInformacionVenta = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel10.setBackground(new java.awt.Color(204, 204, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("VENTA");
        jPanel10.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 490, 40));

        jbtnRealizarCalculo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnRealizarCalculo.setText("Realizar Calculo");
        jPanel10.add(jbtnRealizarCalculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 160, 40));

        jbtnImprimirVenta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnImprimirVenta.setText("Imprimir Boleta de Venta");
        jPanel10.add(jbtnImprimirVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 230, 40));

        jblCantidadProductos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jblCantidadProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblCantidadProductos.setText("Cantidad");
        jPanel10.add(jblCantidadProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 80, -1));
        jPanel10.add(jtxtCantidadProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 120, 30));

        jLabel72.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel72.setText("SubTotal:");
        jPanel10.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));
        jPanel10.add(jtxtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 100, 20));
        jPanel10.add(jtxtIGV, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 100, 20));

        jLabel73.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel73.setText("IGV:");
        jPanel10.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 30, 20));

        jLabel74.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel74.setText("Total:");
        jPanel10.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 40, -1));
        jPanel10.add(jtxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 100, 30));

        jLabel30.setText("Importe:");
        jPanel10.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));
        jPanel10.add(jtxtImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 100, -1));

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("INFORMACION DE LOS PRODUCTOS"));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setText("ID Producto:");
        jPanel12.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jtxtIDProductoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtIDProductoVentaActionPerformed(evt);
            }
        });
        jPanel12.add(jtxtIDProductoVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 120, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Descripcion:");
        jPanel12.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, 20));

        jtxtDescripcionVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDescripcionVentaActionPerformed(evt);
            }
        });
        jPanel12.add(jtxtDescripcionVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 120, -1));

        jLabel26.setText("Precio:");
        jPanel12.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 50, -1));
        jPanel12.add(jtxtPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 120, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Stock:");
        jPanel12.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 50, -1));

        jtxtStockVenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel12.add(jtxtStockVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 120, 20));

        jbtnConsultaProductosVenta.setText("CONSULTA");
        jPanel12.add(jbtnConsultaProductosVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jPanel10.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 220, 170));

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder("INFORMACION DE LOS CLIENTES"));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Señor(a):");
        jPanel17.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 70, 20));
        jPanel17.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 100, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("DNI:");
        jPanel17.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 30, 30));
        jPanel17.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 100, 20));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Dirección:");
        jPanel17.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 90, 30));
        jPanel17.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 100, 20));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Cod.Cliente:");
        jPanel17.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 80, -1));
        jPanel17.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 120, 20));
        jPanel17.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 120, 20));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("RUC:");
        jPanel17.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        jbtnConsultaClientesVenta.setText("BD CLIENTE");
        jPanel17.add(jbtnConsultaClientesVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jButton1.setText("Registrar cliente");
        jPanel17.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 130, -1));

        jPanel10.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 410, 170));

        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setText("10121232121");
        jPanel18.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 80, 20));

        jLabel31.setText("RUC:");
        jPanel18.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Boleta de Venta");
        jPanel18.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 120, 20));

        jlblNumBoleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblNumBoleta.setText("Nº");
        jPanel18.add(jlblNumBoleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, 20));

        jPanel10.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, 160, 100));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Fecha:");
        jLabel22.setToolTipText("");
        jPanel10.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 40, -1));
        jPanel10.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 120, 20));

        jtblInformacionVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jtblInformacionVenta);

        jPanel10.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, 210));

        add(jPanel10, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtIDProductoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtIDProductoVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIDProductoVentaActionPerformed

    private void jtxtDescripcionVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDescripcionVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDescripcionVentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField14;
    public javax.swing.JTextField jTextField18;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField3;
    public javax.swing.JTextField jTextField4;
    public javax.swing.JLabel jblCantidadProductos;
    public javax.swing.JButton jbtnConsultaClientesVenta;
    public javax.swing.JButton jbtnConsultaProductosVenta;
    public javax.swing.JButton jbtnImprimirVenta;
    public javax.swing.JButton jbtnRealizarCalculo;
    public javax.swing.JLabel jlblNumBoleta;
    public javax.swing.JTable jtblInformacionVenta;
    public javax.swing.JTextField jtxtCantidadProductos;
    public javax.swing.JTextField jtxtDescripcionVenta;
    public javax.swing.JTextField jtxtIDProductoVenta;
    public javax.swing.JTextField jtxtIGV;
    public javax.swing.JTextField jtxtImporte;
    public javax.swing.JTextField jtxtPrecioVenta;
    public javax.swing.JTextField jtxtStockVenta;
    public javax.swing.JTextField jtxtSubTotal;
    public javax.swing.JTextField jtxtTotal;
    // End of variables declaration//GEN-END:variables
}
