/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISTA;

/**
 *
 * @author User
 */
public class Panel_Dekogar extends javax.swing.JFrame {

    /**
     * Creates new form Panel_Dekogar
     */
    public Panel_Dekogar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jbtnRegistrar = new javax.swing.JButton();
        jbtnEliminar = new javax.swing.JButton();
        jbtnConsultar = new javax.swing.JButton();
        jbtnActualizar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtxtDescripcion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtPrecio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtStock = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jtxtIDProducto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblInformacion = new javax.swing.JTable();
        jlblCantRegistro = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtxtNomCli = new javax.swing.JTextField();
        jtxtdniCli = new javax.swing.JTextField();
        jtxtEmail = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jtxtDireccion = new javax.swing.JTextField();
        jtxtApell = new javax.swing.JTextField();
        jtxtTele = new javax.swing.JTextField();
        jtxtRuc = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblInfoCli = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jbtnGuardarCli = new javax.swing.JButton();
        jbtnCancelarCli = new javax.swing.JButton();
        jtxtSexo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jbtnRealizarCalculo = new javax.swing.JButton();
        jbtnImprimirVenta = new javax.swing.JButton();
        jblCantidadProductos = new javax.swing.JLabel();
        jtxtCantidadProductos = new javax.swing.JTextField();
        jLabel72 = new javax.swing.JLabel();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtIGV = new javax.swing.JTextField();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jtxtImporte = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jbtnAgregarProductosVenta = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtblInformacionVenta = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jbtnConsultaClientesVenta = new javax.swing.JButton();
        jbtnRegistrarClienteVentas = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jtxtIdCliente = new javax.swing.JTextField();
        jtxtNomCli1 = new javax.swing.JTextField();
        jtxtApell1 = new javax.swing.JTextField();
        jtxtSexo1 = new javax.swing.JTextField();
        jtxtdniCli1 = new javax.swing.JTextField();
        jtxtEmail1 = new javax.swing.JTextField();
        jtxtDireccion1 = new javax.swing.JTextField();
        jtxtTele1 = new javax.swing.JTextField();
        jtxtRuc1 = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jlblNumBoleta = new javax.swing.JLabel();
        jdchFechaVenta = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jtxtDNIConsulta = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();
        jbtnGeneroConsulta = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jtblInfoConsulta = new javax.swing.JTable();
        jLabel42 = new javax.swing.JLabel();
        jTextField30 = new javax.swing.JTextField();
        jtxtGeneroConsulta = new javax.swing.JTextField();
        jbtnMostrarTodosClientesConsulta = new javax.swing.JButton();
        jbtnDNIConsulta = new javax.swing.JButton();
        jlblNroConsulta = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtblReportesProductos = new javax.swing.JTable();
        jlblReportes = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtblReportesclientes = new javax.swing.JTable();
        jlblReportesClientes = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane4.setBackground(new java.awt.Color(255, 204, 153));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Detalle del Producto");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 220, 30));

        jPanel8.setBackground(new java.awt.Color(0, 153, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnRegistrar.setText("REGISTRAR");
        jPanel8.add(jbtnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 270, 50));

        jbtnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnEliminar.setText("ELIMINAR");
        jPanel8.add(jbtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 270, 50));

        jbtnConsultar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnConsultar.setText("CONSULTAR");
        jPanel8.add(jbtnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 270, 50));

        jbtnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnActualizar.setText("ACTUALIZAR");
        jPanel8.add(jbtnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 270, 50));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 310, 260));

        jPanel7.setBackground(new java.awt.Color(255, 255, 204));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Descripción:");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, 20));
        jPanel7.add(jtxtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 220, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Precio:");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 80, 40));
        jPanel7.add(jtxtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 240, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Stock:");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 60, 30));
        jPanel7.add(jtxtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 160, 40));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel28.setText("ID Producto:");
        jPanel7.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));
        jPanel7.add(jtxtIDProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 180, 40));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 670, 220));

        jtblInformacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblInformacion);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 980, 340));

        jlblCantRegistro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlblCantRegistro.setForeground(new java.awt.Color(102, 102, 255));
        jlblCantRegistro.setText("Cantidad de Registro");
        jPanel2.add(jlblCantRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 660, 160, -1));

        jTabbedPane4.addTab("PRODUCTOS", jPanel2);

        jPanel6.setBackground(new java.awt.Color(153, 204, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Detalles Del Cliente");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 30));

        jPanel9.setBackground(new java.awt.Color(204, 255, 204));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Nombres:");
        jPanel9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Sexo:");
        jPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 80, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("DNI:");
        jPanel9.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 70, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Email:");
        jPanel9.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 50, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Dirección:");
        jPanel9.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 70, 20));
        jPanel9.add(jtxtNomCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 190, 30));
        jPanel9.add(jtxtdniCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 200, 30));
        jPanel9.add(jtxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 200, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Apellidos:");
        jPanel9.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 80, 20));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Teléfono:");
        jPanel9.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 80, 20));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("RUC:");
        jPanel9.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 60, 20));
        jPanel9.add(jtxtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 200, 30));
        jPanel9.add(jtxtApell, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 220, 30));
        jPanel9.add(jtxtTele, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 220, 30));
        jPanel9.add(jtxtRuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 210, 30));

        jtblInfoCli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtblInfoCli);

        jPanel9.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 1040, 290));

        jPanel11.setBackground(new java.awt.Color(255, 255, 204));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnGuardarCli.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnGuardarCli.setText("GUARDAR");
        jPanel11.add(jbtnGuardarCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 120, 40));

        jbtnCancelarCli.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnCancelarCli.setText("CANCELAR");
        jPanel11.add(jbtnCancelarCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 120, 40));

        jPanel9.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, 280, 250));
        jPanel9.add(jtxtSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        jPanel6.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 1040, 660));

        jTabbedPane4.addTab("CLIENTES", jPanel6);

        jPanel1.add(jTabbedPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1070, 740));

        jTabbedPane3.addTab("MANTENIMIENTO", jPanel1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(204, 204, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("VENTA");
        jPanel10.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 490, 40));

        jbtnRealizarCalculo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnRealizarCalculo.setText("Realizar Calculo");
        jPanel10.add(jbtnRealizarCalculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, 230, 30));

        jbtnImprimirVenta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnImprimirVenta.setText("Imprimir Boleta de Venta");
        jPanel10.add(jbtnImprimirVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, 230, 30));

        jblCantidadProductos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jblCantidadProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblCantidadProductos.setText("Cantidad");
        jPanel10.add(jblCantidadProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 80, -1));
        jPanel10.add(jtxtCantidadProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, 120, 20));

        jLabel72.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel72.setText("SubTotal:");
        jPanel10.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, -1, -1));
        jPanel10.add(jtxtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 110, 20));
        jPanel10.add(jtxtIGV, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, 110, 20));

        jLabel73.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel73.setText("IGV:");
        jPanel10.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 30, 20));

        jLabel74.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel74.setText("Total:");
        jPanel10.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 40, -1));
        jPanel10.add(jtxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, 110, 20));

        jLabel30.setText("Importe:");
        jPanel10.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, -1, -1));
        jPanel10.add(jtxtImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, 120, -1));

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("INFORMACION DE LOS PRODUCTOS"));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setText("ID Producto:");
        jPanel12.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Descripcion:");
        jPanel12.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 80, 20));

        jLabel26.setText("Precio:");
        jPanel12.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 50, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Stock:");
        jPanel12.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 50, -1));

        jbtnAgregarProductosVenta.setText("Agregar Producto");
        jPanel12.add(jbtnAgregarProductosVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        jtblInformacionVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jtblInformacionVenta);

        jPanel12.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 520, 200));

        jLabel1.setText("Nro");
        jPanel12.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jPanel10.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 550, 280));

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder("INFORMACION DE LOS CLIENTES"));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnConsultaClientesVenta.setBackground(new java.awt.Color(153, 153, 153));
        jbtnConsultaClientesVenta.setText("BD CLIENTE");
        jPanel17.add(jbtnConsultaClientesVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 130, -1));

        jbtnRegistrarClienteVentas.setBackground(new java.awt.Color(153, 153, 153));
        jbtnRegistrarClienteVentas.setText("Registrar cliente");
        jPanel17.add(jbtnRegistrarClienteVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 130, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel29.setText("Id Cliente:");
        jPanel17.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText("Nombres:");
        jPanel17.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 80, 20));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel33.setText("Apellidos:");
        jPanel17.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 80, 20));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel34.setText("Sexo:");
        jPanel17.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, 20));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel35.setText("DNI:");
        jPanel17.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 40, -1));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel36.setText("Email:");
        jPanel17.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 50, 20));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel37.setText("Dirección:");
        jPanel17.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 70, 20));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel38.setText("Teléfono:");
        jPanel17.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 70, 20));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel39.setText("RUC:");
        jPanel17.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 60, 20));
        jPanel17.add(jtxtIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 90, 20));
        jPanel17.add(jtxtNomCli1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 90, 20));
        jPanel17.add(jtxtApell1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 90, -1));
        jPanel17.add(jtxtSexo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 112, 90, 20));
        jPanel17.add(jtxtdniCli1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 90, 20));
        jPanel17.add(jtxtEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 120, 20));
        jPanel17.add(jtxtDireccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 120, 20));
        jPanel17.add(jtxtTele1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 120, -1));
        jPanel17.add(jtxtRuc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 120, 20));

        jPanel10.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 550, 170));

        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setText("           RUC: 10121232121");
        jPanel18.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Boleta de Venta");
        jPanel18.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 180, 20));

        jlblNumBoleta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblNumBoleta.setText("Cantidad Boletas:    ");
        jPanel18.add(jlblNumBoleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 170, 20));

        jPanel10.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 190, 100));

        jdchFechaVenta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FECHA DE VENTA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel10.add(jdchFechaVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 190, -1));

        jTabbedPane2.addTab("BOLETA", jPanel10);

        jPanel3.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1060, 720));

        jTabbedPane3.addTab("MOVIMIENTO", jPanel3);

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("CONSULTA DE CLIENTES");
        jPanel4.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 460, 40));

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton1.setText("Mostrar clientes por Genero: ");
        jPanel4.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 210, 30));

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton2.setText("Buscar Clientes por DNI:");
        jPanel4.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 183, 210, 30));
        jPanel4.add(jtxtDNIConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 180, 30));

        jRadioButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton3.setText("Mostrar todos los clientes");
        jRadioButton3.setActionCommand("Mostrar todos los clientes:");
        jPanel4.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 210, 30));

        jbtnGeneroConsulta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnGeneroConsulta.setText("BUSCAR Genero");
        jPanel4.add(jbtnGeneroConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 140, 40));

        jtblInfoConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(jtblInfoConsulta);

        jPanel4.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 1030, 390));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel42.setText("Cantidad de Registros:");
        jPanel4.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 720, 150, 20));
        jPanel4.add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 720, 100, -1));

        jtxtGeneroConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtGeneroConsultaActionPerformed(evt);
            }
        });
        jPanel4.add(jtxtGeneroConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 180, 30));

        jbtnMostrarTodosClientesConsulta.setText("MUESTRA TODO");
        jPanel4.add(jbtnMostrarTodosClientesConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 220, -1));

        jbtnDNIConsulta.setText("BUSCAR DNI");
        jPanel4.add(jbtnDNIConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 140, 30));

        jlblNroConsulta.setText("Cantidad de Consulta:       ");
        jPanel4.add(jlblNroConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 104, 170, 20));

        jTabbedPane3.addTab("CONSULTAS", jPanel4);

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder("REPORTES DE LOS PRODUCTOS"));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtblReportesProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jtblReportesProductos);

        jPanel19.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 710, 230));

        jlblReportes.setText("Cantidad de Reportes:   ");
        jPanel19.add(jlblReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, -1, -1));

        jPanel5.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 880, 260));

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("REPORTES DE CLIENTES"));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtblReportesclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jtblReportesclientes);

        jPanel13.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 27, 700, 240));

        jlblReportesClientes.setText("Cantidad de Clientes:  ");
        jPanel13.add(jlblReportesClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, -1, -1));

        jPanel5.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 880, 280));

        jTabbedPane3.addTab("REPORTES", jPanel5);

        getContentPane().add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1090, 790));

        jMenu1.setText("Registro");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Mantenimiento");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtGeneroConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtGeneroConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtGeneroConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel_Dekogar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel_Dekogar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel_Dekogar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel_Dekogar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel_Dekogar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    public javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTextField jTextField30;
    public javax.swing.JLabel jblCantidadProductos;
    public javax.swing.JButton jbtnActualizar;
    public javax.swing.JButton jbtnAgregarProductosVenta;
    public javax.swing.JButton jbtnCancelarCli;
    public javax.swing.JButton jbtnConsultaClientesVenta;
    public javax.swing.JButton jbtnConsultar;
    public javax.swing.JButton jbtnDNIConsulta;
    public javax.swing.JButton jbtnEliminar;
    public javax.swing.JButton jbtnGeneroConsulta;
    public javax.swing.JButton jbtnGuardarCli;
    public javax.swing.JButton jbtnImprimirVenta;
    public javax.swing.JButton jbtnMostrarTodosClientesConsulta;
    public javax.swing.JButton jbtnRealizarCalculo;
    public javax.swing.JButton jbtnRegistrar;
    public javax.swing.JButton jbtnRegistrarClienteVentas;
    public com.toedter.calendar.JDateChooser jdchFechaVenta;
    public javax.swing.JLabel jlblCantRegistro;
    public javax.swing.JLabel jlblNroConsulta;
    public javax.swing.JLabel jlblNumBoleta;
    public javax.swing.JLabel jlblReportes;
    public javax.swing.JLabel jlblReportesClientes;
    public javax.swing.JTable jtblInfoCli;
    public javax.swing.JTable jtblInfoConsulta;
    public javax.swing.JTable jtblInformacion;
    public javax.swing.JTable jtblInformacionVenta;
    public javax.swing.JTable jtblReportesProductos;
    public javax.swing.JTable jtblReportesclientes;
    public javax.swing.JTextField jtxtApell;
    public javax.swing.JTextField jtxtApell1;
    public javax.swing.JTextField jtxtCantidadProductos;
    public javax.swing.JTextField jtxtDNIConsulta;
    public javax.swing.JTextField jtxtDescripcion;
    public javax.swing.JTextField jtxtDireccion;
    public javax.swing.JTextField jtxtDireccion1;
    public javax.swing.JTextField jtxtEmail;
    public javax.swing.JTextField jtxtEmail1;
    public javax.swing.JTextField jtxtGeneroConsulta;
    public javax.swing.JTextField jtxtIDProducto;
    public javax.swing.JTextField jtxtIGV;
    public javax.swing.JTextField jtxtIdCliente;
    public javax.swing.JTextField jtxtImporte;
    public javax.swing.JTextField jtxtNomCli;
    public javax.swing.JTextField jtxtNomCli1;
    public javax.swing.JTextField jtxtPrecio;
    public javax.swing.JTextField jtxtRuc;
    public javax.swing.JTextField jtxtRuc1;
    public javax.swing.JTextField jtxtSexo;
    public javax.swing.JTextField jtxtSexo1;
    public javax.swing.JTextField jtxtStock;
    public javax.swing.JTextField jtxtSubTotal;
    public javax.swing.JTextField jtxtTele;
    public javax.swing.JTextField jtxtTele1;
    public javax.swing.JTextField jtxtTotal;
    public javax.swing.JTextField jtxtdniCli;
    public javax.swing.JTextField jtxtdniCli1;
    // End of variables declaration//GEN-END:variables
}
